export const SUBMIT_FORM_REQUEST='SUBMIT_FORM_REQUEST';
export const SUBMIT_FORM_SUCCESS='SUBMIT_FORM_SUCCESS';
export const SUBMIT_FORM_FAILED='SUBMIT_FORM_FAILED';

export const GET_CONTACTS_REQUEST='GET_CONTACTS_REQUEST';
export const GET_CONTACTS_SUCCESS='GET_CONTACTS_SUCCESS';
export const GET_CONTACTS_FAILURE='GET_CONTACTS_FAILURE';